using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Manager : MonoBehaviour
{
    /// <summary>
    /// 目搜b配位置，是要b配物w的父
    /// </summary>
    public Transform target;
    /// <summary>
    /// 要b配的模型
    /// </summary>
    public SkinnedMeshRenderer model;
    /// <summary>
    /// o要b配的模型取一名字
    /// </summary>
    public string objName;
    /// <summary>
    /// 具有骨骼信息的模型，新b配的模型需要用已b配的@模型的骨骼碇]自己的骨骼赢
    /// </summary>
    public SkinnedMeshRenderer targetModel;


    // Update is called once per frame
    void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {
            ModelAdder.Replace(target, objName, model, targetModel);
        }
    }
}
